language: node_js
node_js: 
  - "stable"
  - node
install:
  - npm install
script:
  - npm test
  - codecov -f coverage/*.json
deploy:
  provider: npm
  email: "cenietob@gmail.com"
  api_key: "${NPM_API_KEY}"
  on:
    tags: true
    branch: production